#!/usr/bin/env php
<?php

namespace Shimoning\ZipCloud;

require_once __DIR__ . '/vendor/autoload.php';

echo __NAMESPACE__ . " shell\n";
echo "-----\nexample:\n";
echo "\$response = ZipCloud::search('100-0001');\n";
echo "\$response->isSuccess();\n";
echo "\$addresses = \$response->getAddresses();\n\n";

$sh = new \Psy\Shell();

$sh->addCode(sprintf("namespace %s;", __NAMESPACE__));

$sh->run();

echo "\n-----\nBye.\n";
